// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iquiz.proto

package iquiz

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Question struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Question             string   `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	CorrectAnswer        string   `protobuf:"bytes,3,opt,name=correctAnswer,proto3" json:"correctAnswer,omitempty"`
	AnswerOptions        []string `protobuf:"bytes,4,rep,name=answerOptions,proto3" json:"answerOptions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{0}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Question) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *Question) GetCorrectAnswer() string {
	if m != nil {
		return m.CorrectAnswer
	}
	return ""
}

func (m *Question) GetAnswerOptions() []string {
	if m != nil {
		return m.AnswerOptions
	}
	return nil
}

type Answer struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	IsCorrect            bool     `protobuf:"varint,3,opt,name=isCorrect,proto3" json:"isCorrect,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Answer) Reset()         { *m = Answer{} }
func (m *Answer) String() string { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()    {}
func (*Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{1}
}

func (m *Answer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answer.Unmarshal(m, b)
}
func (m *Answer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answer.Marshal(b, m, deterministic)
}
func (m *Answer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answer.Merge(m, src)
}
func (m *Answer) XXX_Size() int {
	return xxx_messageInfo_Answer.Size(m)
}
func (m *Answer) XXX_DiscardUnknown() {
	xxx_messageInfo_Answer.DiscardUnknown(m)
}

var xxx_messageInfo_Answer proto.InternalMessageInfo

func (m *Answer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Answer) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

func (m *Answer) GetIsCorrect() bool {
	if m != nil {
		return m.IsCorrect
	}
	return false
}

type QuizResponse struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Answers              []*Answer `protobuf:"bytes,2,rep,name=answers,proto3" json:"answers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QuizResponse) Reset()         { *m = QuizResponse{} }
func (m *QuizResponse) String() string { return proto.CompactTextString(m) }
func (*QuizResponse) ProtoMessage()    {}
func (*QuizResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{2}
}

func (m *QuizResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuizResponse.Unmarshal(m, b)
}
func (m *QuizResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuizResponse.Marshal(b, m, deterministic)
}
func (m *QuizResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuizResponse.Merge(m, src)
}
func (m *QuizResponse) XXX_Size() int {
	return xxx_messageInfo_QuizResponse.Size(m)
}
func (m *QuizResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuizResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuizResponse proto.InternalMessageInfo

func (m *QuizResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QuizResponse) GetAnswers() []*Answer {
	if m != nil {
		return m.Answers
	}
	return nil
}

type QuestionList struct {
	Questions            []*Question `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QuestionList) Reset()         { *m = QuestionList{} }
func (m *QuestionList) String() string { return proto.CompactTextString(m) }
func (*QuestionList) ProtoMessage()    {}
func (*QuestionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{3}
}

func (m *QuestionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionList.Unmarshal(m, b)
}
func (m *QuestionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionList.Marshal(b, m, deterministic)
}
func (m *QuestionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionList.Merge(m, src)
}
func (m *QuestionList) XXX_Size() int {
	return xxx_messageInfo_QuestionList.Size(m)
}
func (m *QuestionList) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionList.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionList proto.InternalMessageInfo

func (m *QuestionList) GetQuestions() []*Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{4}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Question)(nil), "iquiz.Question")
	proto.RegisterType((*Answer)(nil), "iquiz.Answer")
	proto.RegisterType((*QuizResponse)(nil), "iquiz.QuizResponse")
	proto.RegisterType((*QuestionList)(nil), "iquiz.QuestionList")
	proto.RegisterType((*Void)(nil), "iquiz.Void")
}

func init() { proto.RegisterFile("iquiz.proto", fileDescriptor_1e146b96c1272c15) }

var fileDescriptor_1e146b96c1272c15 = []byte{
	// 284 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xbb, 0x4f, 0xc3, 0x30,
	0x10, 0xc6, 0x9b, 0xc4, 0x0d, 0xc9, 0x85, 0x82, 0x74, 0x48, 0xc8, 0x8a, 0x18, 0x22, 0x0b, 0x89,
	0x08, 0x89, 0x0c, 0x65, 0x66, 0x40, 0x8c, 0x20, 0x50, 0x3d, 0xb0, 0xb7, 0x8d, 0x07, 0x0f, 0xc4,
	0x69, 0x9c, 0x08, 0xa9, 0x23, 0x7f, 0x39, 0xf2, 0x23, 0x4d, 0xdb, 0xcd, 0x77, 0xf7, 0xfb, 0xbe,
	0x7b, 0x18, 0x32, 0xb9, 0x1b, 0xe4, 0xbe, 0x6a, 0x3b, 0xd5, 0x2b, 0x9c, 0xdb, 0x80, 0xfd, 0x05,
	0x90, 0xac, 0x06, 0xa1, 0x7b, 0xa9, 0x1a, 0xbc, 0x82, 0x50, 0xd6, 0x34, 0x28, 0x82, 0x72, 0xce,
	0x43, 0x59, 0x63, 0x0e, 0xc9, 0xce, 0xd7, 0x68, 0x58, 0x04, 0x65, 0xca, 0x0f, 0x31, 0xde, 0xc3,
	0x62, 0xab, 0xba, 0x4e, 0x6c, 0xfb, 0xd7, 0x46, 0xff, 0x8a, 0x8e, 0x46, 0x16, 0x38, 0x4d, 0x1a,
	0x6a, 0x6d, 0x5f, 0x5f, 0xad, 0x51, 0x69, 0x4a, 0x8a, 0xc8, 0x50, 0x27, 0x49, 0xf6, 0x09, 0xb1,
	0xe7, 0xcf, 0x27, 0xb8, 0x85, 0xd8, 0xa1, 0xbe, 0xbf, 0x8f, 0xf0, 0x0e, 0x52, 0xa9, 0xdf, 0x5c,
	0x2b, 0xdb, 0x39, 0xe1, 0x53, 0x82, 0xbd, 0xc3, 0xe5, 0x6a, 0x90, 0x7b, 0x2e, 0x74, 0xab, 0x1a,
	0x2d, 0x10, 0x81, 0x34, 0xeb, 0x1f, 0x61, 0x7d, 0x53, 0x6e, 0xdf, 0xf8, 0x00, 0x17, 0xce, 0x4b,
	0xd3, 0xb0, 0x88, 0xca, 0x6c, 0xb9, 0xa8, 0xdc, 0x79, 0xdc, 0x24, 0x7c, 0xac, 0xb2, 0x17, 0x63,
	0xe6, 0x96, 0xfe, 0x90, 0xba, 0xc7, 0x27, 0x48, 0xc7, 0x23, 0x68, 0x1a, 0x58, 0xe9, 0xb5, 0x97,
	0x8e, 0x1c, 0x9f, 0x08, 0x16, 0x03, 0xf9, 0x56, 0xb2, 0x5e, 0x6e, 0x80, 0x98, 0x99, 0xf0, 0x11,
	0x88, 0xb5, 0xc9, 0xbc, 0xc6, 0x14, 0xf3, 0x9b, 0x33, 0x03, 0x43, 0xb0, 0x19, 0x56, 0x90, 0x1c,
	0x76, 0x98, 0x90, 0x69, 0xb1, 0xfc, 0xd8, 0x84, 0xcd, 0x36, 0xb1, 0xfd, 0xda, 0xe7, 0xff, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x85, 0x01, 0xf4, 0xa1, 0xe9, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QuizClient is the client API for Quiz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QuizClient interface {
	List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*QuestionList, error)
	Response(ctx context.Context, in *QuizResponse, opts ...grpc.CallOption) (*Void, error)
}

type quizClient struct {
	cc *grpc.ClientConn
}

func NewQuizClient(cc *grpc.ClientConn) QuizClient {
	return &quizClient{cc}
}

func (c *quizClient) List(ctx context.Context, in *Void, opts ...grpc.CallOption) (*QuestionList, error) {
	out := new(QuestionList)
	err := c.cc.Invoke(ctx, "/iquiz.Quiz/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quizClient) Response(ctx context.Context, in *QuizResponse, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/iquiz.Quiz/Response", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuizServer is the server API for Quiz service.
type QuizServer interface {
	List(context.Context, *Void) (*QuestionList, error)
	Response(context.Context, *QuizResponse) (*Void, error)
}

func RegisterQuizServer(s *grpc.Server, srv QuizServer) {
	s.RegisterService(&_Quiz_serviceDesc, srv)
}

func _Quiz_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iquiz.Quiz/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServer).List(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

func _Quiz_Response_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuizResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuizServer).Response(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iquiz.Quiz/Response",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuizServer).Response(ctx, req.(*QuizResponse))
	}
	return interceptor(ctx, in, info, handler)
}

var _Quiz_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iquiz.Quiz",
	HandlerType: (*QuizServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Quiz_List_Handler,
		},
		{
			MethodName: "Response",
			Handler:    _Quiz_Response_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iquiz.proto",
}
