// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iquiz.proto

package iquiz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Question struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Question             string   `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	CorrectAnswer        string   `protobuf:"bytes,3,opt,name=correct_answer,json=correctAnswer,proto3" json:"correct_answer,omitempty"`
	AnswerOptions        []string `protobuf:"bytes,4,rep,name=answer_options,json=answerOptions,proto3" json:"answer_options,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Question) Reset()         { *m = Question{} }
func (m *Question) String() string { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()    {}
func (*Question) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{0}
}

func (m *Question) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Question.Unmarshal(m, b)
}
func (m *Question) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Question.Marshal(b, m, deterministic)
}
func (m *Question) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Question.Merge(m, src)
}
func (m *Question) XXX_Size() int {
	return xxx_messageInfo_Question.Size(m)
}
func (m *Question) XXX_DiscardUnknown() {
	xxx_messageInfo_Question.DiscardUnknown(m)
}

var xxx_messageInfo_Question proto.InternalMessageInfo

func (m *Question) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Question) GetQuestion() string {
	if m != nil {
		return m.Question
	}
	return ""
}

func (m *Question) GetCorrectAnswer() string {
	if m != nil {
		return m.CorrectAnswer
	}
	return ""
}

func (m *Question) GetAnswerOptions() []string {
	if m != nil {
		return m.AnswerOptions
	}
	return nil
}

type Answer struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Answer               string   `protobuf:"bytes,2,opt,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Answer) Reset()         { *m = Answer{} }
func (m *Answer) String() string { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()    {}
func (*Answer) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{1}
}

func (m *Answer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Answer.Unmarshal(m, b)
}
func (m *Answer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Answer.Marshal(b, m, deterministic)
}
func (m *Answer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Answer.Merge(m, src)
}
func (m *Answer) XXX_Size() int {
	return xxx_messageInfo_Answer.Size(m)
}
func (m *Answer) XXX_DiscardUnknown() {
	xxx_messageInfo_Answer.DiscardUnknown(m)
}

var xxx_messageInfo_Answer proto.InternalMessageInfo

func (m *Answer) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Answer) GetAnswer() string {
	if m != nil {
		return m.Answer
	}
	return ""
}

type QuizResponse struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Answer               []*Answer `protobuf:"bytes,2,rep,name=answer,proto3" json:"answer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *QuizResponse) Reset()         { *m = QuizResponse{} }
func (m *QuizResponse) String() string { return proto.CompactTextString(m) }
func (*QuizResponse) ProtoMessage()    {}
func (*QuizResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{2}
}

func (m *QuizResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuizResponse.Unmarshal(m, b)
}
func (m *QuizResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuizResponse.Marshal(b, m, deterministic)
}
func (m *QuizResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuizResponse.Merge(m, src)
}
func (m *QuizResponse) XXX_Size() int {
	return xxx_messageInfo_QuizResponse.Size(m)
}
func (m *QuizResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QuizResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QuizResponse proto.InternalMessageInfo

func (m *QuizResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *QuizResponse) GetAnswer() []*Answer {
	if m != nil {
		return m.Answer
	}
	return nil
}

type QuestionList struct {
	Questions            []*Question `protobuf:"bytes,1,rep,name=questions,proto3" json:"questions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *QuestionList) Reset()         { *m = QuestionList{} }
func (m *QuestionList) String() string { return proto.CompactTextString(m) }
func (*QuestionList) ProtoMessage()    {}
func (*QuestionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{3}
}

func (m *QuestionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuestionList.Unmarshal(m, b)
}
func (m *QuestionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuestionList.Marshal(b, m, deterministic)
}
func (m *QuestionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuestionList.Merge(m, src)
}
func (m *QuestionList) XXX_Size() int {
	return xxx_messageInfo_QuestionList.Size(m)
}
func (m *QuestionList) XXX_DiscardUnknown() {
	xxx_messageInfo_QuestionList.DiscardUnknown(m)
}

var xxx_messageInfo_QuestionList proto.InternalMessageInfo

func (m *QuestionList) GetQuestions() []*Question {
	if m != nil {
		return m.Questions
	}
	return nil
}

type Void struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Void) Reset()         { *m = Void{} }
func (m *Void) String() string { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()    {}
func (*Void) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e146b96c1272c15, []int{4}
}

func (m *Void) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Void.Unmarshal(m, b)
}
func (m *Void) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Void.Marshal(b, m, deterministic)
}
func (m *Void) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Void.Merge(m, src)
}
func (m *Void) XXX_Size() int {
	return xxx_messageInfo_Void.Size(m)
}
func (m *Void) XXX_DiscardUnknown() {
	xxx_messageInfo_Void.DiscardUnknown(m)
}

var xxx_messageInfo_Void proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Question)(nil), "iquiz.Question")
	proto.RegisterType((*Answer)(nil), "iquiz.Answer")
	proto.RegisterType((*QuizResponse)(nil), "iquiz.QuizResponse")
	proto.RegisterType((*QuestionList)(nil), "iquiz.QuestionList")
	proto.RegisterType((*Void)(nil), "iquiz.Void")
}

func init() { proto.RegisterFile("iquiz.proto", fileDescriptor_1e146b96c1272c15) }

var fileDescriptor_1e146b96c1272c15 = []byte{
	// 268 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xcd, 0x47, 0x43, 0x33, 0xb1, 0x15, 0x46, 0x90, 0xa5, 0xa7, 0xb0, 0x50, 0xc8, 0xc5,
	0x52, 0xea, 0xc5, 0x8b, 0x07, 0xf1, 0x24, 0x08, 0xd2, 0x15, 0xbc, 0x96, 0xd8, 0x0c, 0x74, 0x0f,
	0x66, 0xd3, 0xec, 0x06, 0xa1, 0x67, 0xff, 0x70, 0xd9, 0x8f, 0xd6, 0xd2, 0x5b, 0xe6, 0xcd, 0xfb,
	0xbd, 0x99, 0xc9, 0x42, 0x21, 0xf7, 0x83, 0x3c, 0x2c, 0xba, 0x5e, 0x19, 0x85, 0x23, 0x57, 0xf0,
	0xdf, 0x08, 0xc6, 0xeb, 0x81, 0xb4, 0x91, 0xaa, 0xc5, 0x29, 0xc4, 0xb2, 0x61, 0x51, 0x19, 0x55,
	0x23, 0x11, 0xcb, 0x06, 0x67, 0x30, 0xde, 0x87, 0x1e, 0x8b, 0xcb, 0xa8, 0xca, 0xc5, 0xa9, 0xc6,
	0x39, 0x4c, 0xb7, 0xaa, 0xef, 0x69, 0x6b, 0x36, 0x75, 0xab, 0x7f, 0xa8, 0x67, 0x89, 0x73, 0x4c,
	0x82, 0xfa, 0xec, 0x44, 0x6b, 0xf3, 0xed, 0x8d, 0xea, 0x2c, 0xa7, 0x59, 0x5a, 0x26, 0xd6, 0xe6,
	0xd5, 0x77, 0x2f, 0xf2, 0x25, 0x64, 0x01, 0xb8, 0xdc, 0xe1, 0x0e, 0xb2, 0x90, 0xef, 0x37, 0x08,
	0x15, 0x7f, 0x85, 0xeb, 0xf5, 0x20, 0x0f, 0x82, 0x74, 0xa7, 0x5a, 0x4d, 0x88, 0x90, 0xb6, 0xf5,
	0x37, 0x39, 0x32, 0x17, 0xee, 0x1b, 0xe7, 0x67, 0x6c, 0x52, 0x15, 0xab, 0xc9, 0xc2, 0xff, 0x01,
	0x3f, 0xea, 0x14, 0xf5, 0x64, 0xa3, 0xfc, 0x59, 0x6f, 0x52, 0x1b, 0xbc, 0x87, 0xfc, 0x78, 0xa6,
	0x66, 0x91, 0x23, 0x6f, 0x02, 0x79, 0xf4, 0x89, 0x7f, 0x07, 0xcf, 0x20, 0xfd, 0x54, 0xb2, 0x59,
	0x3d, 0x42, 0x6a, 0x37, 0xc2, 0x25, 0xc0, 0xcb, 0x8e, 0x6a, 0xf3, 0xb1, 0x23, 0x32, 0x58, 0x04,
	0xd2, 0x5a, 0x66, 0xb7, 0x17, 0x31, 0x76, 0x1c, 0xbf, 0xfa, 0xca, 0xdc, 0x93, 0x3c, 0xfc, 0x05,
	0x00, 0x00, 0xff, 0xff, 0xfe, 0x5b, 0x96, 0xb7, 0xa1, 0x01, 0x00, 0x00,
}
